# SecuriSite-IA User Credentials
# Format: [users.username]
# password = "hashed_password_or_plain_for_demo"
# role = "admin" | "manager" | "viewer"
# full_name = "Display Name"

[users.marc]
password = "securisite2025"
role = "manager"
full_name = "Marc Dubois"
description = "Responsable Sécurité - Chantier Principal"

[users.admin]
password = "BadrEnlaps2025"
role = "badr" 
full_name = "Badr Eddine LEBBAT"
description = "Accès complet au système SecuriSite-IA"

[users.badr]
password = "badr1234"
role = "badr"
full_name = "Badr Eddine LEBBAT"
description = "Développeur SecuriSite-IA"

# Configuration
[config]
session_timeout_minutes = 480  # 8 hours
require_authentication = true
allow_password_reset = false 