"""
SecuriSite-IA: Système Multi-Agent d'Analyse des Risques sur Chantier
Auto-generated by Claude Code - Enlaps Technical Test 2025
"""

import asyncio
import sys
from pathlib import Path

# Ensure we can find our modules
current_dir = Path(__file__).parent
sys.path.insert(0, str(current_dir))

from securisite.orchestrator import main

if __name__ == "__main__":
    # Run the complete system
    asyncio.run(main())